export const challenges = [
  // ❤️ GOOD DEED
  {
    id: 'gd-1',
    title: 'Give a genuine compliment',
    description: 'Give someone a genuine, specific compliment today. Make it sincere and about something meaningful.',
    category: 'good-deed',
    difficulty: 'easy',
    estimated_time: '5-10 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'gd-2',
    title: 'Thank someone from your past',
    description: 'Reach out to someone who helped you in the past and thank them. Tell them specifically what they did and how it impacted you.',
    category: 'good-deed',
    difficulty: 'easy',
    estimated_time: '15-20 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'gd-3',
    title: 'Buy someone a small treat',
    description: 'Buy someone a coffee, snack, or small meal. It could be a friend, colleague, or even a stranger.',
    category: 'good-deed',
    difficulty: 'easy',
    estimated_time: '10-15 minutes',
    requires_other_person: true,
    requires_money: true,
    requires_location: false,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'gd-4',
    title: 'Send an encouraging message',
    description: 'Send an encouraging message to someone who needs it. Think of someone going through a tough time.',
    category: 'good-deed',
    difficulty: 'easy',
    estimated_time: '10 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'gd-5',
    title: 'Leave a generous tip',
    description: 'Leave a generous tip for someone in the service industry with a kind note.',
    category: 'good-deed',
    difficulty: 'easy',
    estimated_time: '5 minutes',
    requires_other_person: true,
    requires_money: true,
    requires_location: false,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },

  // 🤝 HELP SOMEONE
  {
    id: 'hs-1',
    title: 'Help carry something heavy',
    description: 'Help someone carrying groceries, moving furniture, or struggling with a heavy load.',
    category: 'help-someone',
    difficulty: 'easy',
    estimated_time: '10-15 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'hs-2',
    title: 'Teach someone a skill',
    description: 'Share your knowledge. Teach someone something you know how to do.',
    category: 'help-someone',
    difficulty: 'medium',
    estimated_time: '30-60 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'hs-3',
    title: 'Help a neighbor with a task',
    description: 'Offer to help a neighbor with something practical - yard work, tech help, or a household task.',
    category: 'help-someone',
    difficulty: 'medium',
    estimated_time: '30-60 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'hs-4',
    title: 'Give directions or assistance',
    description: 'Help someone who looks lost or confused. Give clear, patient directions or assistance.',
    category: 'help-someone',
    difficulty: 'easy',
    estimated_time: '5-10 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },

  // 🌱 COMMUNITY
  {
    id: 'cm-1',
    title: 'Pick up litter',
    description: 'Spend 15 minutes picking up litter in a public area. Bring a bag and gloves.',
    category: 'community',
    difficulty: 'easy',
    estimated_time: '15-20 minutes',
    requires_other_person: false,
    requires_money: false,
    requires_location: true,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'cm-2',
    title: 'Donate useful items',
    description: 'Donate clothes, books, or items you no longer need to a local charity or shelter.',
    category: 'community',
    difficulty: 'medium',
    estimated_time: '1-2 hours',
    requires_other_person: false,
    requires_money: false,
    requires_location: true,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'cm-3',
    title: 'Support a local business',
    description: 'Visit a local small business and make a purchase. Leave a positive review.',
    category: 'community',
    difficulty: 'easy',
    estimated_time: '20-30 minutes',
    requires_other_person: false,
    requires_money: true,
    requires_location: true,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },

  // 💚 GIVE
  {
    id: 'gv-1',
    title: 'Donate to a charity',
    description: 'Donate $5 or more to a charity of your choice. Research and find one that matters to you.',
    category: 'give',
    difficulty: 'easy',
    estimated_time: '10 minutes',
    requires_other_person: false,
    requires_money: true,
    requires_location: false,
    proof_type: 'receipt',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'gv-2',
    title: 'Pay for someone behind you',
    description: 'Pay for the order of the person behind you in line at a coffee shop or drive-through.',
    category: 'give',
    difficulty: 'easy',
    estimated_time: '5 minutes',
    requires_other_person: true,
    requires_money: true,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'gv-3',
    title: 'Give your time',
    description: 'Volunteer an hour of your time to help someone or an organization.',
    category: 'give',
    difficulty: 'medium',
    estimated_time: '1-2 hours',
    requires_other_person: false,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },

  // 🎨 CREATIVE
  {
    id: 'cr-1',
    title: 'Create art for someone',
    description: 'Make a drawing, painting, or craft for someone. It doesn\'t have to be perfect - it just has to be thoughtful.',
    category: 'creative',
    difficulty: 'medium',
    estimated_time: '30-60 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'cr-2',
    title: 'Write an encouraging note',
    description: 'Write a heartfelt, encouraging note and give it to someone or leave it somewhere for a stranger to find.',
    category: 'creative',
    difficulty: 'easy',
    estimated_time: '15 minutes',
    requires_other_person: false,
    requires_money: false,
    requires_location: false,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'cr-3',
    title: 'Create something that makes someone smile',
    description: 'Make something creative - a funny video, a meme, a song, anything - specifically to brighten someone\'s day.',
    category: 'creative',
    difficulty: 'medium',
    estimated_time: '30-60 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },

  // 😂 FUN
  {
    id: 'fn-1',
    title: 'Make someone laugh',
    description: 'Tell a joke, share a funny story, or do something silly to make someone genuinely laugh today.',
    category: 'fun',
    difficulty: 'easy',
    estimated_time: '5-10 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'fn-2',
    title: 'Organize a surprise gathering',
    description: 'Organize a small surprise gathering or activity for a friend or colleague. Keep it simple and fun.',
    category: 'fun',
    difficulty: 'medium',
    estimated_time: '1-2 hours',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'photo',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'fn-3',
    title: 'Share something that made you smile',
    description: 'Share a funny video, meme, or story with someone who needs a laugh today.',
    category: 'fun',
    difficulty: 'easy',
    estimated_time: '5 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },

  // 🧠 LEARN & SHARE
  {
    id: 'ls-1',
    title: 'Learn and teach something new',
    description: 'Learn something new today and teach it to someone else. It could be a fact, skill, or insight.',
    category: 'learn-share',
    difficulty: 'medium',
    estimated_time: '30-60 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'ls-2',
    title: 'Share a valuable resource',
    description: 'Share a book, article, video, or resource that changed your perspective with someone who might benefit.',
    category: 'learn-share',
    difficulty: 'easy',
    estimated_time: '10-15 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
  {
    id: 'ls-3',
    title: 'Mentor someone',
    description: 'Offer to mentor someone in an area where you have experience. Have a meaningful conversation.',
    category: 'learn-share',
    difficulty: 'medium',
    estimated_time: '30-60 minutes',
    requires_other_person: true,
    requires_money: false,
    requires_location: false,
    proof_type: 'story',
    safety_level: 'safe',
    active: true,
  },
]

export const categories = [
  {
    id: 'good-deed',
    name: 'Good Deed',
    emoji: '❤️',
    description: 'Small acts of kindness',
  },
  {
    id: 'help-someone',
    name: 'Help Someone',
    emoji: '🤝',
    description: 'Practical help and support',
  },
  {
    id: 'community',
    name: 'Community',
    emoji: '🌱',
    description: 'Actions that benefit your community',
  },
  {
    id: 'give',
    name: 'Give',
    emoji: '💚',
    description: 'Donate time, money, or resources',
  },
  {
    id: 'creative',
    name: 'Creative',
    emoji: '🎨',
    description: 'Create something kind',
  },
  {
    id: 'fun',
    name: 'Fun',
    emoji: '😂',
    description: 'Bring joy and laughter',
  },
  {
    id: 'learn-share',
    name: 'Learn & Share',
    emoji: '🧠',
    description: 'Share knowledge and wisdom',
  },
  {
    id: 'random',
    name: 'Random',
    emoji: '🌍',
    description: 'Surprise me',
  },
]
